<Project Sdk="Microsoft.NET.Sdk">

  

    <ItemGroup>
      <!-- FrameworkReference da acceso a TODOS los tipos de ASP.NET Core
         (IEndpointRouteBuilder, IExceptionHandler, ProblemDetails, etc.)
         SIN convertir el proyecto en una app ejecutable. -->
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

  

  <ItemGroup>
    <ProjectReference Include="..\EShop.BuildingBlocks.Application\EShop.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\EShop.BuildingBlocks.Domain\EShop.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

</Project>
